name:  Controller workflow entry after receiving push event
on:
  push:
    branches:
      - main
    paths:
      - "controllers/**"

jobs:
  start-workflow:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/controller.yml
    with:
      needs_push: true
      needs_cluster_image: true